export const testJson: CalendarGroup = {
  total: 0,
  list: [
    { id: 1, yn: false },
    { id: 2, yn: false },
    { id: 3, yn: false },
    { id: 4, yn: false },
    { id: 5, yn: false },
    { id: 6, yn: false },
    { id: 7, yn: false },
    { id: 8, yn: false },
    { id: 9, yn: false },
    { id: 10, yn: false },
    { id: 11, yn: false },
    { id: 12, yn: false },
    { id: 13, yn: false },
    { id: 14, yn: false },
    { id: 15, yn: false },
    { id: 16, yn: false },
    { id: 17, yn: false },
    { id: 18, yn: false },
    { id: 19, yn: false },
    { id: 20, yn: false },
    { id: 21, yn: false },
    { id: 22, yn: false },
    { id: 23, yn: false },
    { id: 24, yn: false },
    { id: 25, yn: false },
    { id: 26, yn: false },
    { id: 27, yn: false },
    { id: 28, yn: false },
  ],
};
